# Generated by Django 5.1.7 on 2025-03-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
