# Generated by Django 5.1.7 on 2025-04-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0002_alter_tarefa_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_atualizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(default='pendente', max_length=50),
        ),
    ]
